version: '3.7'

services:
  zeppelin-distribution:
    image: zeppelin-distribution
    command: package -U
    build:
      context: ./dist
      args: 
        - ZEPPELIN_BRANCH_VERSION=$ZEPPELIN_BRANCH_VERSION
        - ZEPPELIN_REPOSITORY=$ZEPPELIN_REPOSITORY
    environment:
      - MAVEN_PROJECT=$MAVEN_PROJECT
      - MAVEN_PROFILE=$MAVEN_PROFILE
    volumes:
      - "maven-repo:/root/.m2"
      - "distro:/workspace/zeppelin/zeppelin-distribution/target"
  
  zeppelin-binary:
    image: zeppelin
    build:
      context: ./binary
      args:
        - ZEPPELIN_VERSION=$ZEPPELIN_VERSION
    ports:
      - "$ZEPPELIN_WEBUI_PORT:$ZEPPELIN_WEBUI_PORT"
  
  zeppelin-binary-armv8:
    image: zeppelin
    build:
      context: ./binary
      args:
        - ARCH=aarch64
        - CPU=arm
        - miniconda_sha256=ccbac800a2d897218dde1df3711d26299a083ca0beb118edf62cf8f3d9516da8
        - ZEPPELIN_VERSION=$ZEPPELIN_VERSION
    ports:
      - "$ZEPPELIN_WEBUI_PORT:$ZEPPELIN_WEBUI_PORT"

volumes:
  maven-repo:
  distro: