version: '3.7'

services:
  zeppelin-distribution:
    image: zeppelin-distribution
    build:
      context: ./dist
      args: 
        - ZEPPELIN_VERSION=$ZEPPELIN_BRANCH_VERSION
    environment:
      - MAVEN_PROJECT=$MAVEN_PROJECT
    volumes:
      - "maven-repo:/root/.m2"
      - "distro:/workspace/zeppelin/zeppelin-distribution/target"

  zeppelin-binary:
    image: zeppelin
    build:
      context: ./binary
      args: 
        - ZEPPELIN_VERSION=$ZEPPELIN_VERSION

volumes:
  maven-repo:
  distro: