version: '3.7'

services:
  zeppelin-distribution:
    image: zeppelin-distribution
    build:
      context: ./dist
      args: 
        - ZEPPELIN_VERSION: $ZEPPELIN_VERSION
    environment:
      - MAVEN_PROJECT
    volumes:
      - "maven-repo:/root/.m2"
      - "distro:/workspace/zeppelin/zeppelin-distribution/target"

volumes:
  maven-repo:
  distro: