version: '3.7'

services:
  zeppelin-distribution:
    image: zeppelin-distribution
    build: ./dist
    volumes:
      - "maven-repo:/root/.m2"
      - "distro:/workspace/zeppelin/zeppelin-distribution/target"

volumes:
  maven-repo:
  distro: